---
title: "2019-04-10!"
author: "jasmine"
date: "2019/4/10"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

You can also embed plots, for example:

```{r pressure, echo=FALSE}
plot(pressure)
```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.

```{r}
library(stringr)
```

```{r}
install.packages("stringr")
```

```{r}
course <- c("個體經濟學","投資學","總體經濟學")
course
str_subset(course,"經濟學")
```
```{r}
course <- c("個體經濟學","投資學","總體經濟學")
course
str_detect(course,"經濟學")
```

```{r}
studentID<-c(
  '410177115','410176080','410174233','410177011','410182045','410176014')
studentID
major<- str_sub(studentID,5,6)
major
```
```{r}
studentID<-c(
  '410177115','410176080','410174233','410177011','410182045','410176014')
studentID
入學年<-str_sub(studentID,2,4)
入學年
```



```{r}
month <-c("2","7","9")
day <-c("15","11","23")
char1 <- c("月","月","月")
char2 <- c("日","日","日")
month
char1
day 
char2
str_c(month,char1,day,char2)
```

```{r}
str_c(month,c("月"),day,c("日"))
str_c(month,"月",day,"日")
```

```{r}
month
day
str_c(month,day, sep="-")
```

```{r}
library(readr)
```

```{r}
install.packages("readr")
```

```{r}
library(readr)
githubData <- read_csv("https://raw.githubusercontent.com/tpemartin/github-data/master/githubData.csv")
username <- githubData$`GitHub username`[11:16]
reponame <- githubData$`GitHub repo name`[11:16]
str_c("https://github.com",username,reponame,sep="/")
```

```{r}
birthday[1:2]
y <-str_sub(birthday[1:2],1,4)
m <-str_sub(birthday[1:2],5,6)
d <-str_sub(birthday[1:2],7,8)
y
m
d
bday <-str_c("西元"，y，"年"，m,"月"，d，"日") 
bday
```


```{r}
library(readr)
filmVotingData <- read_csv("https://raw.githubusercontent.com/tpemartin/github-data/master/%E7%AC%AC%E4%B8%89%E5%B1%86%E7%B6%93%E6%BF%9F%E6%92%AD%E5%AE%A2%E7%AB%B6%E8%B3%BD%E5%8F%83%E8%B3%BD%E4%BD%9C%E5%93%81%E6%8A%95%E7%A5%A8%E7%B5%90%E6%9E%9C%E6%A8%A3%E6%9C%AC%20-%20Sheet1.csv")
birthday<-filmVotingData$`出生西元年月日（驗證本人用）`
```

```{r}
民國年月<-c("099/01","099/02","099/03")
```

```{r}
c <- as.integer(a)+1911
c
```
```{r}
民國年月<-c("099/01","099/02","099/03")
aa <- str_sub(民國年月,1,3)
intaa <- as.integer(aa)
west <- intaa+1911
chawest <- as.character(west)
answer2 <-str_c(chawest,str_sub(民國年月,4,6))
answer2 
```

# vectors
```{r}
a <-c(1:3)
typeof(a)
a
```

```{r}
aWithNames <-c(
  a1=1,
  a2=2,
  a3=3
)
typeof(aWithNames)
aWithNames
```

List
```{r}
b1 <-list("a","b",c(1:10),TRUE)
typeof(b1)
b1
```

```{r}

```

