---
title: '2019-03-13'
author: "jasmine"
date: "3/13/2019"
output: html_document
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
a <- 2
3 -> b
4 -> c
d <- 5
```
```{r}
65 + b
```

```{r}
a
b
c
```
```{r}
`a`
`b`
```
```{r}
學期107我的平均成績<-92
```

```{r}
`107學期我的平均成績`<-92
```

```{r}
class(a)
```

```{r}
a<-5
a2<-5L
```

```{r}
class(a2)
```

```{r}
aVector<-c(5,6,7)
a2Vector<-c(5L,6L,7L)
```

```{r}
class(aVector)
```
```{r}
class(a2Vector)
```
```{r}
dialogue <- c("小明說：'明天不用上課。'",
               "小花說：'真的嗎？'")

cat(dialogue, sep="\n")
```


```{r}
studentMajors <- factor(
  c("經濟系", "經濟系", "法律系")
)
```

```{r}
typeof(studentMajors)
```

```{r}
levels(studentMajors)
```

```{r}
studentMajors
```

```{r}
as.integer(studentMajors)
```

```{r}
birthplace <- factor(c('台中','台中','台北','台北','台北'))
birthplace
as.integer(birthplace)
```

```{r}

```
```{r}
library(lubridate)
```


```{r}
dtObject<-ymd_hms("1970-01-01 00:02:53") 
```

```{r}
dtObjectVector<-ymd_hms(
  c("1970-01-01 00:02:53",
    "1980-02-11 11:25:22")
)
```

```{r}
Sys.timezone(Asia/Taipei)
```

```{r}
twDateTime <- ymd_hms("2019-03-18 14:04:00", tz="Asia/Taipei")
```

```{r}
dtObjectVector<-ymd_hms(
  c("1970-01-01 00:02:53",
    "1980-02-11 11:25:22")
)

class(dtObject)

dtObject

typeof(dtObject)

as.double(dtObject)
```

```{r}
Sys.timezone()
```
```{r}

```

```{r}
LisbonDateTime <- with_tz(twDateTime,tzone="Europe/Lisbon")

LisbonDateTime
```

